[package]
name = "gis-partitioner"
version = "0.1.0"
edition = "2021"
authors = ["Jesper Fjellin"]

[dependencies]
geo = "0.27"
geojson = "0.24"
rstar = "0.11"
clap = { version = "4.4", features = ["derive"] }
serde_json = "1.0"
quick-xml = "0.31"
